openapi: 3.0.0
info:
  title: webNote API
  version: 1.0.0
  description: API for note management (user registration, CRUD notes)
servers:
  - url: http://127.0.0.1:8000/
paths:
  /api/notes/:
    get:
      summary: Get all notes for the authenticated user
      tags: [Notes]
      security: [{ bearerAuth: [] }]
      responses:
        '200':
          description: List of notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      summary: Create a new note
      tags: [Notes]
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteCreate'
      responses:
        '201':
          description: Note created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
  /api/notes/delete/{id}:
    delete:
      summary: Delete a note by ID
      tags: [Notes]
      security: [{ bearerAuth: [] }]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Note deleted
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          maxLength: 50
        content:
          type: string
        time_creation:
          type: string
          format: date-time
        author:
          type: integer
    NoteCreate:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required: [title, content]